name: spotify_clone
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Thin.otf
          weight: 100
        - asset: assets/fonts/Gotham-XLight.otf
          weight: 200
        - asset: assets/fonts/Gotham-Light.otf
          weight: 300
        - asset: assets/fonts/GothamBook.ttf
          weight: 400
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/GothamBold.ttf
          weight: 700
        - asset: assets/fonts/Gotham-Black.otf
          weight: 900
